import React from "react";

const wrapperStyle = {
  display: "flex",
  flexDirection: "column",
  alignItems: "center",
};

function IrregularVerbs() {
  return (
    <div style={wrapperStyle}>
      <h1>
        List of <b>Irregular Verbs</b>
      </h1>
      <table border="1" cellPadding="2" cellSpacing="2" bordercolor="#000000">
        <tbody>
          <tr>
            <th>
              <strong>Infinitive</strong>
            </th>
            <th>
              <strong>Simple Past Tense</strong>
            </th>
            <th>
              <strong>Past Participle</strong>
            </th>
          </tr>
          <tr>
            <td>awake</td>
            <td>awoke</td>
            <td>awoken</td>
          </tr>
          <tr>
            <td>be</td>
            <td>was, were</td>
            <td>been</td>
          </tr>
          <tr>
            <td>bear</td>
            <td>bore</td>
            <td>born</td>
          </tr>
          <tr>
            <td>beat</td>
            <td>beat</td>
            <td>beat</td>
          </tr>
          <tr>
            <td>become</td>
            <td>became</td>
            <td>become</td>
          </tr>
          <tr>
            <td>begin</td>
            <td>began</td>
            <td>begun</td>
          </tr>
          <tr>
            <td>bend</td>
            <td>bent</td>
            <td>bent</td>
          </tr>
          <tr>
            <td>beset</td>
            <td>beset</td>
            <td>beset</td>
          </tr>
          <tr>
            <td>bet</td>
            <td>bet</td>
            <td>bet</td>
          </tr>
          <tr>
            <td>bid</td>
            <td>bid / bade</td>
            <td>bid / bidden</td>
          </tr>
          <tr>
            <td>bind</td>
            <td>bound</td>
            <td>bound</td>
          </tr>
          <tr>
            <td>bite</td>
            <td>bit </td>
            <td>bitten</td>
          </tr>
          <tr>
            <td>bleed</td>
            <td>bled</td>
            <td>bled</td>
          </tr>
          <tr>
            <td>blow</td>
            <td>blew</td>
            <td>blown</td>
          </tr>
          <tr>
            <td>break</td>
            <td>broke</td>
            <td>broken</td>
          </tr>
          <tr>
            <td>breed</td>
            <td>bred</td>
            <td>bred</td>
          </tr>
          <tr>
            <td>bring</td>
            <td>brought</td>
            <td>brought</td>
          </tr>
          <tr>
            <td>broadcast</td>
            <td>broadcast</td>
            <td>broadcast</td>
          </tr>
          <tr>
            <td>build</td>
            <td>built</td>
            <td>built</td>
          </tr>
          <tr>
            <td>burn</td>
            <td>burned / burnt</td>
            <td>burned / burnt</td>
          </tr>
          <tr>
            <td>burst</td>
            <td>burst</td>
            <td>burst</td>
          </tr>
          <tr>
            <td>buy</td>
            <td>bought</td>
            <td>bought</td>
          </tr>
          <tr>
            <td>cast</td>
            <td>cast</td>
            <td>cast</td>
          </tr>
          <tr>
            <td>catch</td>
            <td>caught</td>
            <td>caught</td>
          </tr>
          <tr>
            <td>choose</td>
            <td>chose</td>
            <td>chosen</td>
          </tr>
          <tr>
            <td>cling</td>
            <td>clung</td>
            <td>clung</td>
          </tr>
          <tr>
            <td>come</td>
            <td>came</td>
            <td>come</td>
          </tr>
          <tr>
            <td>cost</td>
            <td>cost</td>
            <td>cost</td>
          </tr>
          <tr>
            <td>creep</td>
            <td>crept</td>
            <td>crept</td>
          </tr>
          <tr>
            <td>cut</td>
            <td>cut</td>
            <td>cut</td>
          </tr>
          <tr>
            <td>deal</td>
            <td>dealt</td>
            <td>dealt</td>
          </tr>
          <tr>
            <td>dig</td>
            <td>dug</td>
            <td>dug</td>
          </tr>
          <tr>
            <td>dive</td>
            <td>dived / dove</td>
            <td>dived</td>
          </tr>
          <tr>
            <td>do</td>
            <td>did</td>
            <td>done</td>
          </tr>
          <tr>
            <td>draw</td>
            <td>drew</td>
            <td>drawn</td>
          </tr>
          <tr>
            <td>dream</td>
            <td>dreamed / dreamt</td>
            <td>dreamed / dreamt</td>
          </tr>
          <tr>
            <td>drive</td>
            <td>drove</td>
            <td>driven</td>
          </tr>
          <tr>
            <td>drink</td>
            <td>drank</td>
            <td>drunk</td>
          </tr>
          <tr>
            <td>eat</td>
            <td>ate</td>
            <td>eaten</td>
          </tr>
          <tr>
            <td>fall</td>
            <td>fell</td>
            <td>fallen</td>
          </tr>
          <tr>
            <td>feed</td>
            <td>fed</td>
            <td>fed</td>
          </tr>
          <tr>
            <td>feel</td>
            <td>felt</td>
            <td>felt</td>
          </tr>
          <tr>
            <td>fight</td>
            <td>fought</td>
            <td>fought</td>
          </tr>
          <tr>
            <td>find</td>
            <td>found</td>
            <td>found</td>
          </tr>
          <tr>
            <td>fit</td>
            <td>fit</td>
            <td>fit</td>
          </tr>
          <tr>
            <td>flee</td>
            <td>fled</td>
            <td>fled</td>
          </tr>
          <tr>
            <td>fling</td>
            <td>flung</td>
            <td>flung</td>
          </tr>
          <tr>
            <td>fly</td>
            <td>flew</td>
            <td>flown</td>
          </tr>
          <tr>
            <td>forbid</td>
            <td>forbade</td>
            <td>forbidden</td>
          </tr>
          <tr>
            <td>forget</td>
            <td>forgot</td>
            <td>forgotten</td>
          </tr>
          <tr>
            <td>forego (forgo)</td>
            <td>forewent</td>
            <td>foregone</td>
          </tr>
          <tr>
            <td>forgive</td>
            <td>forgave</td>
            <td>forgiven</td>
          </tr>
          <tr>
            <td>forsake</td>
            <td>forsook</td>
            <td>forsaken</td>
          </tr>
          <tr>
            <td>freeze</td>
            <td>froze</td>
            <td>frozen</td>
          </tr>
          <tr>
            <td>get</td>
            <td>got</td>
            <td>gotten</td>
          </tr>
          <tr>
            <td>give</td>
            <td>gave</td>
            <td>given</td>
          </tr>
          <tr>
            <td>go</td>
            <td>went</td>
            <td>gone</td>
          </tr>
          <tr>
            <td>grind</td>
            <td>ground</td>
            <td>ground</td>
          </tr>
          <tr>
            <td>grow</td>
            <td>grew</td>
            <td>grown</td>
          </tr>
          <tr>
            <td>hang</td>
            <td>hung</td>
            <td>hung</td>
          </tr>
          <tr>
            <td>hear</td>
            <td>heard</td>
            <td>heard</td>
          </tr>
          <tr>
            <td>hide</td>
            <td>hid</td>
            <td>hidden</td>
          </tr>
          <tr>
            <td>hit</td>
            <td>hit</td>
            <td>hit</td>
          </tr>
          <tr>
            <td>hold</td>
            <td>held</td>
            <td>held</td>
          </tr>
          <tr>
            <td>hurt</td>
            <td>hurt</td>
            <td>hurt</td>
          </tr>
          <tr>
            <td>keep</td>
            <td>kept</td>
            <td>kept</td>
          </tr>
          <tr>
            <td>kneel</td>
            <td>knelt</td>
            <td>knelt</td>
          </tr>
          <tr>
            <td>knit</td>
            <td>knit</td>
            <td>knit</td>
          </tr>
          <tr>
            <td>know</td>
            <td>knew</td>
            <td>know</td>
          </tr>
          <tr>
            <td>lay</td>
            <td>laid</td>
            <td>laid</td>
          </tr>
          <tr>
            <td>lead</td>
            <td>led</td>
            <td>led</td>
          </tr>
          <tr>
            <td>leap</td>
            <td>leaped / leapt</td>
            <td>leaped / leapt</td>
          </tr>
          <tr>
            <td>learn</td>
            <td>learned / learnt</td>
            <td>learned / learnt</td>
          </tr>
          <tr>
            <td>leave</td>
            <td>left</td>
            <td>left</td>
          </tr>
          <tr>
            <td>lend</td>
            <td>lent</td>
            <td>lent</td>
          </tr>
          <tr>
            <td>let</td>
            <td>let</td>
            <td>let</td>
          </tr>
          <tr>
            <td>lie</td>
            <td>lay</td>
            <td>lain</td>
          </tr>
          <tr>
            <td>light</td>
            <td>lighted / lit</td>
            <td>lighted / lit</td>
          </tr>
          <tr>
            <td>lose</td>
            <td>lost</td>
            <td>lost</td>
          </tr>
          <tr>
            <td>make</td>
            <td>made</td>
            <td>made</td>
          </tr>
          <tr>
            <td>mean</td>
            <td>meant</td>
            <td>meant</td>
          </tr>
          <tr>
            <td>meet</td>
            <td>met</td>
            <td>met</td>
          </tr>
          <tr>
            <td>misspell</td>
            <td>misspelled / misspelt</td>
            <td>misspelled / misspelt</td>
          </tr>
          <tr>
            <td>mistake</td>
            <td>mistook</td>
            <td>mistaken</td>
          </tr>
          <tr>
            <td>mow</td>
            <td>mowed</td>
            <td>mowed / mown</td>
          </tr>
          <tr>
            <td>overcome</td>
            <td>overcame</td>
            <td>overcome</td>
          </tr>
          <tr>
            <td>overdo</td>
            <td>overdid</td>
            <td>overdone</td>
          </tr>
          <tr>
            <td>overtake</td>
            <td>overtook</td>
            <td>overtaken</td>
          </tr>
          <tr>
            <td>overthrow</td>
            <td>overthrew</td>
            <td>overthrown</td>
          </tr>
          <tr>
            <td>pay</td>
            <td>paid</td>
            <td>paid</td>
          </tr>
          <tr>
            <td>plead</td>
            <td>pleaded / pled</td>
            <td>pleaded / pled</td>
          </tr>
          <tr>
            <td>prove</td>
            <td>proved</td>
            <td>proved / proven</td>
          </tr>
          <tr>
            <td>put</td>
            <td>put</td>
            <td>put</td>
          </tr>
          <tr>
            <td>quit</td>
            <td>quit</td>
            <td>quit</td>
          </tr>
          <tr>
            <td>read</td>
            <td>read</td>
            <td>read</td>
          </tr>
          <tr>
            <td>rid</td>
            <td>rid</td>
            <td>rid</td>
          </tr>
          <tr>
            <td>ride</td>
            <td>rode</td>
            <td>ridden</td>
          </tr>
          <tr>
            <td>ring</td>
            <td>rang</td>
            <td>rung</td>
          </tr>
          <tr>
            <td>rise</td>
            <td>rose</td>
            <td>risen</td>
          </tr>
          <tr>
            <td>run</td>
            <td>ran</td>
            <td>run</td>
          </tr>
          <tr>
            <td>saw</td>
            <td>sawed</td>
            <td>sawed / sawn</td>
          </tr>
          <tr>
            <td>say</td>
            <td>said</td>
            <td>said</td>
          </tr>
          <tr>
            <td>see</td>
            <td>saw</td>
            <td>seen</td>
          </tr>
          <tr>
            <td>seek</td>
            <td>sought</td>
            <td>sought</td>
          </tr>
          <tr>
            <td>sell</td>
            <td>sold</td>
            <td>sold</td>
          </tr>
          <tr>
            <td>send</td>
            <td>sent</td>
            <td>sent</td>
          </tr>
          <tr>
            <td>set</td>
            <td>set</td>
            <td>set</td>
          </tr>
          <tr>
            <td>sew</td>
            <td>sewed</td>
            <td>sewed / sewn</td>
          </tr>
          <tr>
            <td>shake</td>
            <td>shook</td>
            <td>shaken</td>
          </tr>
          <tr>
            <td>shave</td>
            <td>shaved</td>
            <td>shaved / shaven</td>
          </tr>
          <tr>
            <td>shear</td>
            <td>sheared / shore</td>
            <td>sheared / shorn</td>
          </tr>
          <tr>
            <td>shed</td>
            <td>shed</td>
            <td>shed</td>
          </tr>
          <tr>
            <td>shine</td>
            <td>shone</td>
            <td>shone</td>
          </tr>
          <tr>
            <td>shoe</td>
            <td>shod</td>
            <td>shod</td>
          </tr>
          <tr>
            <td>shoot</td>
            <td>shot</td>
            <td>shot</td>
          </tr>
          <tr>
            <td>show</td>
            <td>showed</td>
            <td>showed / shown</td>
          </tr>
          <tr>
            <td>shrink</td>
            <td>shrank</td>
            <td>shrunk</td>
          </tr>
          <tr>
            <td>shut</td>
            <td>shut</td>
            <td>shut</td>
          </tr>
          <tr>
            <td>sing</td>
            <td>sang</td>
            <td>sung</td>
          </tr>
          <tr>
            <td>sink</td>
            <td>sank</td>
            <td>sunk</td>
          </tr>
          <tr>
            <td>sit</td>
            <td>sat</td>
            <td>sat</td>
          </tr>
          <tr>
            <td>sleep</td>
            <td>slept</td>
            <td>slept</td>
          </tr>
          <tr>
            <td>slay</td>
            <td>slew</td>
            <td>slain</td>
          </tr>
          <tr>
            <td>slide</td>
            <td>slid</td>
            <td>slid</td>
          </tr>
          <tr>
            <td>sling</td>
            <td>slung</td>
            <td>slung</td>
          </tr>
          <tr>
            <td>slit</td>
            <td>slit</td>
            <td>slit</td>
          </tr>
          <tr>
            <td>smite</td>
            <td>smote</td>
            <td>smitten</td>
          </tr>
          <tr>
            <td>sow</td>
            <td>sowed</td>
            <td>sowed / sown</td>
          </tr>
          <tr>
            <td>speak</td>
            <td>spoke</td>
            <td>spoken</td>
          </tr>
          <tr>
            <td>speed</td>
            <td>sped</td>
            <td>sped</td>
          </tr>
          <tr>
            <td>spend</td>
            <td>spent</td>
            <td>spent</td>
          </tr>
          <tr>
            <td>spill</td>
            <td>spilled / spilt</td>
            <td>spilled / spilt</td>
          </tr>
          <tr>
            <td>spin</td>
            <td>spun</td>
            <td>spun</td>
          </tr>
          <tr>
            <td>spit</td>
            <td>spit / spat</td>
            <td>spit</td>
          </tr>
          <tr>
            <td>split</td>
            <td>split</td>
            <td>split</td>
          </tr>
          <tr>
            <td>spread</td>
            <td>spread</td>
            <td>spread</td>
          </tr>
          <tr>
            <td>spring</td>
            <td>sprang / sprung</td>
            <td>sprung</td>
          </tr>
          <tr>
            <td>stand</td>
            <td>stood</td>
            <td>stood</td>
          </tr>
          <tr>
            <td>steal</td>
            <td>stole</td>
            <td>stolen</td>
          </tr>
          <tr>
            <td>stick</td>
            <td>stuck</td>
            <td>stuck</td>
          </tr>
          <tr>
            <td>sting</td>
            <td>stung</td>
            <td>stung</td>
          </tr>
          <tr>
            <td>stink</td>
            <td>stank</td>
            <td>stunk</td>
          </tr>
          <tr>
            <td>stride</td>
            <td>strode</td>
            <td>stridden</td>
          </tr>
          <tr>
            <td>strike</td>
            <td>struck</td>
            <td>struck</td>
          </tr>
          <tr>
            <td>string</td>
            <td>strung</td>
            <td>strung</td>
          </tr>
          <tr>
            <td>strive</td>
            <td>strove</td>
            <td>striven</td>
          </tr>
          <tr>
            <td>swear</td>
            <td>swore</td>
            <td>sworn</td>
          </tr>
          <tr>
            <td>sweep</td>
            <td>swept</td>
            <td>swept</td>
          </tr>
          <tr>
            <td>swell</td>
            <td>swelled</td>
            <td>swelled / swollen&nbsp;</td>
          </tr>
          <tr>
            <td>swim</td>
            <td>swam</td>
            <td>swum</td>
          </tr>
          <tr>
            <td>swing</td>
            <td>swung</td>
            <td>swung</td>
          </tr>
          <tr>
            <td>take</td>
            <td>took</td>
            <td>taken</td>
          </tr>
          <tr>
            <td>teach</td>
            <td>taught</td>
            <td>taught</td>
          </tr>
          <tr>
            <td>tear</td>
            <td>tore</td>
            <td>torn</td>
          </tr>
          <tr>
            <td>tell</td>
            <td>told</td>
            <td>told</td>
          </tr>
          <tr>
            <td>think</td>
            <td>thought</td>
            <td>thought</td>
          </tr>
          <tr>
            <td>thrive</td>
            <td>thrived / throve</td>
            <td>thrived</td>
          </tr>
          <tr>
            <td>throw</td>
            <td>threw</td>
            <td>thrown</td>
          </tr>
          <tr>
            <td>thrust</td>
            <td>thrust</td>
            <td>thrust</td>
          </tr>
          <tr>
            <td>tread</td>
            <td>trod</td>
            <td>trodden</td>
          </tr>
          <tr>
            <td>understand</td>
            <td>understood</td>
            <td>understood</td>
          </tr>
          <tr>
            <td>uphold</td>
            <td>upheld</td>
            <td>upheld</td>
          </tr>
          <tr>
            <td>upset</td>
            <td>upset</td>
            <td>upset</td>
          </tr>
          <tr>
            <td>wake</td>
            <td>woke</td>
            <td>woken</td>
          </tr>
          <tr>
            <td>wear</td>
            <td>wore</td>
            <td>worn</td>
          </tr>
          <tr>
            <td>weave</td>
            <td>weaved / wove</td>
            <td>weaved / woven</td>
          </tr>
          <tr>
            <td>wed</td>
            <td>wed</td>
            <td>wed</td>
          </tr>
          <tr>
            <td>weep</td>
            <td>wept</td>
            <td>wept</td>
          </tr>
          <tr>
            <td>wind</td>
            <td>wound</td>
            <td>wound</td>
          </tr>
          <tr>
            <td>win</td>
            <td>won</td>
            <td>won</td>
          </tr>
          <tr>
            <td>withhold</td>
            <td>withheld</td>
            <td>withheld</td>
          </tr>
          <tr>
            <td>withstand</td>
            <td>withstood</td>
            <td>withstood</td>
          </tr>
          <tr>
            <td>wring</td>
            <td>wrung</td>
            <td>wrung</td>
          </tr>
          <tr>
            <td>write</td>
            <td>wrote</td>
            <td>written</td>
          </tr>
        </tbody>
      </table>
    </div>
  );
}

export default IrregularVerbs;
